name: 👷 AppImage CI

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    types: [opened, synchronize, labeled]
  workflow_dispatch:

jobs:
  BuildAppImage:

    runs-on: ubuntu-latest

    steps:
    -
      uses: actions/checkout@v2
      with:
        lfs: true
    -
      name: 🔧 Configure
      run: |
        mkdir -p build
        docker run --rm -v $(pwd):/src/ --device /dev/fuse --cap-add SYS_ADMIN --security-opt apparmor:unconfined reivilo1234/qt-linux-cmake:ubuntu20-qt6.6.2 \
          cmake \
          -DQATERIALHOTRELOAD_IGNORE_ENV=ON \
          -B ./build/ -S .
    -
      name: 🔨 Build QaterialHotReloadApp
      run: |
        docker run --rm -v $(pwd):/src/ --device /dev/fuse --cap-add SYS_ADMIN --security-opt apparmor:unconfined reivilo1234/qt-linux-cmake:ubuntu20-qt6.6.2 \
          cmake --build build --target "QaterialHotReloadApp" --config "Release" -j $(nproc)
    -
      name: 🚀 Deploy QaterialHotReload AppImage
      run: |
        docker run --rm -v $(pwd):/src/ --device /dev/fuse --cap-add SYS_ADMIN --security-opt apparmor:unconfined reivilo1234/qt-linux-cmake:ubuntu20-qt6.6.2 \
          cmake --build build --target "QaterialHotReloadAppAppImage" --config "Release" -j $(nproc)
    -
      name: Get Name of Artifact
      run: |
        ARTIFACT_PATHNAME=$(ls build/*.AppImage | head -n 1)
        ARTIFACT_NAME=$(basename $ARTIFACT_PATHNAME)
        echo "ARTIFACT_NAME=${ARTIFACT_NAME}" >> $GITHUB_ENV
        echo "ARTIFACT_PATHNAME=${ARTIFACT_PATHNAME}" >> $GITHUB_ENV
    -
      name: 📦 Upload QaterialHotReload AppImage
      uses: actions/upload-artifact@v2
      with:
        name: QaterialHotReload.AppImage
        path: ${{ env.ARTIFACT_PATHNAME }}
    -
      name: 🚀 Upload Release Asset
      if: github.event_name == 'release' && startsWith(github.ref, 'refs/tags/v')
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ env.ARTIFACT_PATHNAME }}
        asset_name: QaterialHotReload.AppImage
        asset_content_type: application/vnd.appimage
