name: 👷 Windows CI

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    types: [opened, synchronize, labeled]
  workflow_dispatch:

jobs:
  BuildWindows:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        qt-version: ['6.6.2']
        build-type: ['Release']
    steps:
      -
        uses: actions/checkout@v4
        with:
          lfs: true
      -
        name: ⬆ Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ matrix.qt-version }}
          cache: true
          modules: 'qtcharts qtdatavis3d qtvirtualkeyboard qtwebengine qtnetworkauth qtquick3d qt5compat qtshadertools'
      -
        name: 🔧 Configure
        run: |
          mkdir -p build
          cmake -DQATERIALHOTRELOAD_IGNORE_ENV=ON -DCMAKE_BUILD_TYPE="${{ matrix.build-type }}" -B build -S .
        shell: bash
      -
        name: 🔨 Build Qaterial
        run: cmake --build build --target "Qaterial" --config "${{ matrix.build-type }}" -j
      -
        name: 🔨 Build QaterialHotReloadApp
        run: cmake --build build --target "QaterialHotReloadApp" --config "${{ matrix.build-type }}" -j
      -
        name: 🔨 Build QaterialHotReload Installer
        run: cmake --build build --target "QaterialHotReloadAppInstallerX64" --config "${{ matrix.build-type }}" -j
      -
        name: 📦 Upload QaterialHotReload Installer
        uses: actions/upload-artifact@v2
        with:
          name: QaterialHotReloadInstallerX64${{ matrix.build-type }}.exe
          path: build/QaterialHotReloadAppInstallerX64${{ matrix.build-type }}.exe
      -
        name: 🚀 Upload Release Asset
        if: github.event_name == 'release' && startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: build/QaterialHotReloadAppInstallerX64${{ matrix.build-type }}.exe
          asset_name: QaterialHotReloadInstallerX64${{ matrix.build-type }}.exe
          asset_content_type: application/vnd.microsoft.portable-executable
